apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installplan-approver
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
    verbs:
      - update
      - patch
      - list
      - get
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - list
      - get
