apiVersion: v1
kind: Pod
metadata:
  name: ose-cli
  namespace: openshift-cnv
spec:
  containers:
    - args:
        - sleep
        - inf
      image: registry.redhat.io/openshift4/ose-cli:v4.7
      name: ose-cli
  serviceAccountName: installplan-approver
